### ISSUE TITLE
La recherche de films ne marche plus

### ISSUE THREAD

**Issue by ssacard** [ssacard/mon-dvdclub#33]
Je récupère le JS dans le navigateur, au lieu d'injecter le code HTML dans la page....

http://screencast.com/t/5Yi8EpzZMm

Tu as la même chose ?

**Comment by ssacard** [comment]
Erreur sur la method /search 

2011-07-14T17:24:52+00:00 app[web.1]: 
2011-07-14T17:24:52+00:00 app[web.1]: 
2011-07-14T17:24:52+00:00 app[web.1]: Processing DvdsController#search (for 82.235.179.109 at 2011-07-14 10:24:52) [POST]
2011-07-14T17:24:52+00:00 app[web.1]:   Parameters: {"title"=>"big fish", "authenticity_token"=>"3vgeJVwsZksxDf6vJE6F86LVnqteRr84DiCRwqzco1Q="}
2011-07-14T17:24:52+00:00 app[web.1]:   User Load (1.2ms)   SELECT \* FROM "users" WHERE ("users"."id" = 1) LIMIT 1
2011-07-14T17:24:53+00:00 heroku[router]: POST www.mondvdclub.fr/dvds/search dyno=web.1 queue

2011-07-14T17:24:53+00:00 app[web.1]: 
2011-07-14T17:24:53+00:00 app[web.1]: NoMethodError (undefined method `search_and_convert' for #<Amazon::Element:0x7fe48a506218>):
2011-07-14T17:24:53+00:00 app[web.1]:   lib/amazon_store.rb:35:in`search'
2011-07-14T17:24:53+00:00 app[web.1]:   .bundle/gems/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:77:in `each_with_index'
2011-07-14T17:24:53+00:00 app[web.1]:   lib/amazon_store.rb:26:in`each'
2011-07-14T17:24:53+00:00 app[web.1]:   lib/amazon_store.rb:26:in `each_with_index'
2011-07-14T17:24:53+00:00 app[web.1]:   lib/amazon_store.rb:26:in`search'
2011-07-14T17:24:53+00:00 app[web.1]:   app/controllers/dvds_controller.rb:13:in `search'
2011-07-14T17:24:53+00:00 app[web.1]:   .bundle/gems/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in`send'
2011-07-14T17:24:53+00:00 app[web.1]:   .bundle/gems/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in `perform_action_without_filters'
2011-07-14T17:24:53+00:00 app[web.1]:   .bundle/gems/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:87:in`dispatch'
2011-07-14T17:24:53+00:00 app[web.1]:   .bundle/gems/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:121:in `_call'
2011-07-14T17:27:11+00:00 app[web.1]: 
2011-07-14T17:27:11+00:00 app[web.1]:

**Comment by ssacard** [comment]
Je suis en train de corriger  : l'API d'Amazon semble être maintenant sensible à la casse. 
=> Corrigé dans  lib/amazon_store.rb  ( Commit: d3952a76b2d9f05dbffa9b884eef350adebb9728)

**Comment by ssacard** [comment]
=> Encore un problème d'encoding ? Le problème semble être dans la partie :render ? 

Processing ApplicationController#create to  (for 127.0.0.1 at 2011-07-14 20:59:11) [POST]
  Parameters: {"largeimage"=>"http://ecx.images-amazon.com/images/I/41S66BXBKNL.jpg", "actors"=>["Anne Sylvestre"], "smallimage"=>"http://ecx.images-amazon.com/images/I/41S66BXBKNL._SL75_.jpg", "title"=>"Anne Sylvestre : A l'Auditorium Saint-Germain des Pr&#xE9;s", "director"=>"", "authenticity_token"=>"cSkgrOg4/o71WZvinfg0dLyntKpSPtUujbUGS9L94Ks=", "url"=>"http://www.amazon.fr/Anne-Sylvestre-lAuditorium-Saint-Germain-Pr%C3%A9s/dp/B000222XL0%3FSubscriptionId%3DAKIAJQNSSS77ZI7WVKOA%26tag%3Dws%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB000222XL0", "asin"=>"B000222XL0", "owner_id"=>2, "manufacturer"=>"Universal Music", "description"=>""}

ArgumentError (interning empty string):
  haml (3.1.2) rails/./lib/haml/helpers/action_view_mods.rb:13:in `render'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:92:in`each'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:23:in`start'
  /Users/kelxiii/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/webrick/server.rb:82:in `start'

/!\ FAILSAFE /!\  Thu Jul 14 20:59:11 +0200 2011
  Status: 500 Internal Server Error
  interning empty string

**Comment by oelmekki** [comment]
Ok, je viens de regarder un peu, j'ai également cette erreur.

Comme précédemment, le pb est qu'on utilise la dernière version de la gem amazon, et qu'elle n'est pas compatible avec le code développé pour la gem utilisée au moment du développement.

La bonne nouvelle, c'est qu'avec bundler, on peut maintenant forcer les versions. Je me demande si ça ne vaut pas le coup d'essayer de retrouver la version compatible, en attandant l'update général du site.

**Comment by oelmekki** [comment]
Ok, en croisant l'introduction de la gem dans le code ( https://github.com/ssacard/mon-dvdclub/blame/master/config/environment.rb , ligne 27 ) et la date des versions de amazon-ecs, je pense pouvoir dire que la version utilisée à la base est la 0.5.7 ( https://github.com/jugend/amazon-ecs/commits/v0.5.7 ).

Est-ce que tu es ok pour que je revert tes modifs de conf d'hier et que je force cette version?

**Comment by ssacard** [comment]
Oui tu as raison - du coup il faut sûrement revenir sur mes modifs. 

Merci !

**Comment by ssacard** [comment]
Yes !

**Comment by oelmekki** [comment]
Fixed.

à la racine de l'app, il faut que tu lances : 
    bundle install

Puis que tu relances le server.

**Comment by ssacard** [comment]
Ok merci ! Je ne suis pas chez moi, peux-tu pousser en prod pour que j'invite des testeurs ?

**Comment by oelmekki** [comment]
Yep, c'est fait :)

Ah d'ailleurs, je ne sais pas quelle politique de déploiement tu veux suivre. J'ai l'habitude de déployer chaque fois qu'un point stable est atteint. Est-ce que tu préfères qu'on temporise pour faire des "releases", avec un nombre de changements notables?

**Comment by ssacard** [comment]
Pour moi l'objectif était de faire tester rapidement, donc de corriger toutes les petites régressions + les pages de Il faut que je finisse de tester, mais ça me parait bon.

Apres effectivement on passera en mode livraison fréquentes, mais stables. Je veux bien attendre Rails3 + tests pour ça.
